version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: rshiny-nginx
    ports:
      - "8181:80"
    volumes:
      - ./rshinyapp:/var/www/html/shared
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - rshiny-network

networks:
  rshiny-network:
    driver: bridge

